# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f4E6SZvnxdW65DLpPdS9QqyKzaPqcV-e
"""

import numpy as np

import pandas as pd
import matplotlib.pyplot as plt

dataset=pd.read_csv("Salary_Data.csv")

print(dataset)

# divide the dataset into X & y
# where X-> independent variable 
# and y-> dependent variable

X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,1].values

# divide the dataset into training and testing dataset
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test= train_test_split(X,y,train_size=2/3,random_state=0)
X_test

# implement classifier into Simple Linear Regression
from sklearn.linear_model import LinearRegression

simplelinearRegression = LinearRegression()
simplelinearRegression.fit(X_train,y_train)

y_predict=simplelinearRegression.predict(X_test)
y_predict

# implement the graph for Simple Linear Regression
plt.scatter(X_train,y_train,color='red')
plt.plot(X_train,simplelinearRegression.predict(X_train))
plt.show()

